---
- name: Create Namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ ocm_hub_kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: open-cluster-management

- name: Create OperatorGroup
  kubernetes.core.k8s:
    kubeconfig: "{{ ocm_hub_kubeconfig }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: open-cluster-management-group
        namespace: open-cluster-management
      spec:
        targetNamespaces:
          - open-cluster-management

- name: Operator Subscription Exists
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: advanced-cluster-management
    namespace: open-cluster-management
  register: ocm_operator_sub

- name: Assumed Installing
  set_fact:
    upgrading: false

- name: Subscription Exists, but Test if New Version
  block:
    - name: Get Currently Installed Subscription
      set_fact:
        ocm_installedCSV: "{{ lookup('k8s', kubeconfig=ocm_hub_kubeconfig, api_version='operators.coreos.com/v1alpha1', kind='Subscription', namespace='open-cluster-management', resource_name='advanced-cluster-management') | json_query(query) }}"
      vars:
        query: "status.installedCSV"

    - name: Is New Version
      set_fact:
        upgrading: "{{ ocm_installedCSV != 'advanced-cluster-management.v' + ocm_version }}"
  when: ocm_operator_sub.resources | length != 0

- name: "[Install] Set ocm_startingCSV"
  set_fact:
    ocm_startingCSV: "advanced-cluster-management.v{{ ocm_version }}"
  when: not upgrading

- name: "[Upgrade] Set ocm_startingCSV"
  set_fact:
    ocm_startingCSV: "{{ ocm_installedCSV }}"
  when: upgrading

- name: Plan Approval Automatic for Install/Upgrade
  set_fact:
    ocm_plan_approval: 'Automatic'

- name: Create Operator Subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ ocm_hub_kubeconfig }}"
    state: present
    template: operator.yml.j2
    wait: true
    wait_condition:
      type: 'CatalogSourcesUnhealthy'
      reason: 'AllCatalogSourcesHealthy'
      status: 'False'

- name: Confirm Install of MultiClusterHub
  block:
    - name: "[Install] Wait for MultiClusterHub (MCH) CRD"
      kubernetes.core.k8s_info:
        kubeconfig: "{{ ocm_hub_kubeconfig }}"
        kind: CustomResourceDefinition
        name: multiclusterhubs.operator.open-cluster-management.io
        wait: true
        wait_condition:
          type: 'Established'
          reason: 'InitialNamesAccepted'
          status: 'True'
        wait_timeout: 300

    - name: "[Install] Setup MultiClusterHub (MCH) instance"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ ocm_hub_kubeconfig }}"
        template: multiclusterhub.yml.j2
        wait: true
        wait_condition:
          type: 'Complete'
          reason: 'ComponentsAvailable'
          status: 'True'
        wait_timeout: 600
  when: not upgrading

- name: Confirm Upgrade of MultiClusterHub
  block:
    - name: "[Upgrade] Wait until old OCM Operator Removed"
      kubernetes.core.k8s_info:
        kubeconfig: "{{ ocm_hub_kubeconfig }}"
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        name: "{{ ocm_installedCSV }}"
        namespace: open-cluster-management
      register: ocm_old_operator
      until: ocm_old_operator.resources | length == 0
      retries: 15
      delay: 20

    - name: "[Upgrade] Wait for MultiClusterHub (MCH) instance"
      kubernetes.core.k8s_info:
        kubeconfig: "{{ ocm_hub_kubeconfig }}"
        api_version: operator.open-cluster-management.io/v1
        kind: MultiClusterHub
        name: multiclusterhub
        namespace: open-cluster-management
        wait: true
        wait_condition:
          type: 'Complete'
          reason: 'ComponentsAvailable'
          status: 'True'
        wait_timeout: 600
  when: upgrading

- name: "Set Plan Approval"
  set_fact:
    ocm_plan_approval: "{{ ocm_lockversion | ternary('Manual', 'Automatic', 'Manual') }}"

- name: "Update Operator Subscription with Plan Approval"
  kubernetes.core.k8s:
    kubeconfig: "{{ ocm_hub_kubeconfig }}"
    state: present
    template: operator.yml.j2