- name: "Install RHACM on  {{ target_hosts }} host group"
  hosts: "{{ target_hosts }}"
  connection: local
  gather_facts: false
  tasks:
    - include_tasks: ..roles/install-rhacm/tasks/main.yml
      vars:
        ocm_install_catalog: redhat-operators
        ocm_install_catalog_ns: openshift-marketplace
        ocm_channel: release-2.3
        ocm_version: 2.3.3
        ocm_lockversion: false
        rbac_template: ../k8s-rbac/cluster-admin
        serviceaccount_name: cluster-admin
    - include_tasks: ../roles/k8s-cluster-access/tasks/generate-kubeconfig.yml
      ignore_errors: true
